"use client";

import { useEffect, useState } from "react";

type Vertical={id:"commerce"|"crypto";name:string;description:string;automation:string[]};
type Snapshot={source:string;verticals:Vertical[];revenue:{commerce:number;crypto:number;total:number;currency:string};deals:Record<string,unknown>[];orders:Record<string,unknown>[];ledger:{amount:number;currency:string;source:string;recorded_at:string}[];affiliateCommissions:number;safety:string};

export default function EarningPage(){
 const [data,setData]=useState<Snapshot|null>(null); const [error,setError]=useState("");
 const load=()=>fetch('/api/earning',{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Không tải được dữ liệu');return j}).then(j=>{setData(j);setError('')}).catch(e=>setError(e.message));
 useEffect(()=>{load();const id=setInterval(load,10000);return()=>clearInterval(id)},[]);
 if(error&&!data)return <main className="main"><div className="error">{error}</div></main>;
 if(!data)return <main className="main"><div className="card">Đang tải dữ liệu thực tế từ Supabase…</div></main>;
 return <main className="main"><header className="top"><div><div className="eyebrow">Owner Dashboard · Realtime</div><h1 className="title">Revenue & Inbound Payments</h1><p className="sub">Dữ liệu hiển thị trực tiếp từ Supabase. Tự động làm mới mỗi 10 giây.</p></div><a className="primary" href="/payments">Inbound Payments</a></header><nav className="earning-nav"><a href="/earning">Revenue</a><a href="/payments">Inbound Payment</a><a href="/autopilot">CEO Agent</a></nav><section className="grid"><Metric label="Verified revenue" value={`${data.revenue.total.toLocaleString()} ${data.revenue.currency}`}/><Metric label="Affiliate commissions" value={`${data.affiliateCommissions.toLocaleString()} ${data.revenue.currency}`}/><Metric label="Verified payment events" value={String(data.ledger.length)}/><Metric label="Safety firewall" value={data.safety}/></section><div className="verticals">{data.verticals.map(v=><section className="card" key={v.id}><div className="eyebrow">{v.id==='commerce'?'COMMERCE / AFFILIATE':'CRYPTO'}</div><h2>{v.name}</h2><p className="sub">{v.description}</p><ul>{v.automation.map(x=><li key={x}>{x}</li>)}</ul><div className="status ready">DATABASE CONNECTED</div></section>)}</div><section className="panel"><div className="panelhead"><strong>Verified revenue ledger</strong><span className="label">Source: {data.source}</span></div><table className="table"><thead><tr><th>Source</th><th>Amount</th><th>Currency</th><th>Recorded</th></tr></thead><tbody>{data.ledger.map((r,i)=><tr key={`${r.recorded_at}-${i}`}><td>{r.source}</td><td><strong>{Number(r.amount).toLocaleString()}</strong></td><td>{r.currency}</td><td>{new Date(r.recorded_at).toLocaleString('vi-VN')}</td></tr>)}{data.ledger.length===0&&<tr><td colSpan={4}>Chưa có giao dịch thành công được xác thực.</td></tr>}</tbody></table></section>{error&&<div className="error" style={{marginTop:12}}>{error}</div>}<section className="card firewall" style={{marginTop:18}}><h2>🛡️ Compliance & Safety Firewall</h2><p className="sub">Doanh thu chỉ đến từ payment events đã xác thực. Không có withdrawal, transfer, trading hoặc quyền điều khiển tài khoản ngân hàng trong AgentFlow.</p></section></main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="card"><div className="label">{label}</div><div className="metric">{value}</div></div>}
