"use client";
import { useEffect, useMemo, useState } from "react";

type Agent={id:string;name:string;role?:string;status:string;revenue?:number};
type RevenueRow={id:string;transactionCode:string;amount:number;status:string;provider:string;createdAt:string};
const NAMES=["SalesBot","SupportAI","DataAnalyzer","ContentWriter","ChatBot","LeadGen","EmailAI","SocialMedia","Analytics","CRM","Billing","Inventory","Research","Design","Code","QA","HR","Finance","Marketing","CustomerService"];
const ICONS=["↗","◌","⌁","✦","◈","◎","✉","◇","◒","▣","◫","▤","⌕","✎","⌘","✓","♙","◐","◆","◉"];
const seed=NAMES.map((name,i)=>({id:name.toLowerCase(),name,role:"AI Agent",status:i<12?"running":"stopped",revenue:0}));

export default function AgentFlowShell({view}:{view:"overview"|"agents"|"workflows"|"history"}){
 const [agents,setAgents]=useState<Agent[]>(seed),[revenue,setRevenue]=useState(0),[payments,setPayments]=useState(0),[history,setHistory]=useState<RevenueRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;const load=async()=>{try{const [ar,rr]=await Promise.all([fetch("/api/agents",{cache:"no-store"}),fetch("/api/earning",{cache:"no-store"})]);const ad=ar.ok?await ar.json():[];const rd=await rr.json();if(!rr.ok)throw new Error(rd.error||"Không thể tải dữ liệu doanh thu");if(alive){setAgents(Array.isArray(ad)&&ad.length?ad:seed);setRevenue(Number(rd.revenue?.total||0));const ps=Array.isArray(rd.payments)?rd.payments.filter((p:any)=>p.status==="success"):[];setPayments(ps.length);setHistory(Array.isArray(rd.history)?rd.history:[]);setError("")}}catch(e){if(alive)setError(e instanceof Error?e.message:"Không thể tải dữ liệu")}finally{if(alive)setLoading(false)}};load();const t=setInterval(load,10000);return()=>{alive=false;clearInterval(t)}},[]);
 const fleet=useMemo(()=>NAMES.map((name,i)=>({...seed[i],...(agents.find(a=>a.name?.toLowerCase()===name.toLowerCase()||a.id?.toLowerCase()===name.toLowerCase())||{})})),[agents]);
 const running=fleet.filter(a=>a.status==="running"||a.status==="ready").length;
 const nav=[ ["/","⌂","Tổng quan"],["/agents","◈","AI Agents"],["/workflows","⌁","Workflows"],["/history","◷","Lịch sử"] ];
 const money=(n:number)=>`${Number(n||0).toLocaleString("vi-VN")} ₫`;
 return <div className="shell"><aside className="side"><div className="brand"><img src="/avatar.svg" alt="AgentFlow"/><span>Agent<span>Flow</span></span></div><nav className="nav">{nav.map(([href,icon,label])=><a key={href} className={(view==="overview"&&href==="/")||(href.includes(view))?"active":""} href={href}>{icon} {label}</a>)}</nav><div className="side-status">● Safety Firewall ON</div></aside><main className="main"><header className="top"><div className="mobile-brand"><img src="/avatar.svg" alt=""/><div><div className="eyebrow">AI CONTROL CENTER</div><h1 className="title">AgentFlow</h1></div></div><span className="safety-badge">● Live · cập nhật 10s</span></header>{error&&<div className="error">{error}</div>}
 {view==="overview"&&<Overview revenue={revenue} running={running} stopped={20-running} payments={payments} loading={loading} money={money}/>}
 {view==="agents"&&<Agents fleet={fleet} loading={loading} money={money}/>}
 {view==="workflows"&&<Workflows/>}
 {view==="history"&&<History rows={history} loading={loading} money={money}/>} 
 </main><nav className="bottom-nav" aria-label="Điều hướng chính">{nav.map(([href,icon,label])=><a key={href} className={(view==="overview"&&href==="/")||(href.includes(view))?"active":""} href={href}>{icon}<small>{label}</small></a>)}</nav></div>
}
function Overview({revenue,running,stopped,payments,loading,money}:{revenue:number;running:number;stopped:number;payments:number;loading:boolean;money:(n:number)=>string}){return <><section className="overview-grid"><div className="panel cash-widget"><div className="eyebrow">DÒNG TIỀN THỰC TẾ</div><h2>{loading?"…":money(revenue)}</h2><span className="live-badge">● Supabase LIVE</span><div className="cash-meta"><div><span>Payments thành công</span><strong>{payments}</strong></div><div><span>AI đang chạy</span><strong>{running}/20</strong></div></div></div><div className="panel system-widget"><div className="panelhead"><strong>Trạng thái hệ thống</strong><span className="live-badge">LIVE</span></div><div className="system-row"><span>Database</span><b>🟢 Connected</b></div><div className="system-row"><span>PayOS</span><b>🟢 Webhook</b></div><div className="system-row"><span>Safety Firewall</span><b>🟢 Active</b></div><div className="status-pills"><span className="status-pill running">🟢 {running} Đang chạy</span><span className="status-pill stopped">🔴 {stopped} Đã dừng</span></div></div></section><section className="overview-quick panel"><div><div className="eyebrow">QUICK CONTROL</div><h2>Trung tâm điều hành</h2><p>Doanh thu, đội ngũ AI và quy trình được tách riêng để anh kiểm soát nhanh mà không bị quá tải thông tin.</p></div><div className="quick-actions"><a href="/agents">Quản lý AI →</a><a href="/workflows">Xem Workflows →</a><a href="/history">Kiểm tra giao dịch →</a></div></section></>}
function Agents({fleet,loading,money}:{fleet:Agent[];loading:boolean;money:(n:number)=>string}){return <section className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">AUTONOMOUS FLEET</div><h2>20 AI Agents</h2><p>Mỗi Agent có trạng thái riêng và được đồng bộ tự động.</p></div><span className="label">Tự cập nhật 10 giây</span></div><div className="ai-grid">{loading?NAMES.map((_,i)=><div className="skeleton" key={i}/>):fleet.map((a,i)=><article className="ai-card card" key={a.id}><div className="ai-icon">{ICONS[i]}</div><div className="ai-name">{a.name}</div><div className="ai-status"><span className={`status-dot ${a.status==="running"||a.status==="ready"?"on":""}`}/>{a.status==="running"||a.status==="ready"?"Đang chạy":"Đã dừng"}</div><div className="ai-revenue">+{money(Number(a.revenue||0))}</div></article>)}</div></section>}
function Workflows(){const items=[["Customer Acquisition","Lead → tư vấn → payment → webhook","Active"],["E-Commerce Autopilot","Tìm deal → nội dung → theo dõi chuyển đổi","Active"],["Affiliate Autopilot","Theo dõi click → đơn hàng → commission","Active"],["Revenue Reconciliation","PayOS webhook → payment_events → revenue_ledger","Protected"]];return <section className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">AUTOMATION</div><h2>Workflows</h2><p>Chỉ hiển thị nhiệm vụ và quy trình, không pha trộn dữ liệu doanh thu.</p></div></div><div className="workflow-list">{items.map(([name,desc,status])=><article className="panel workflow-card" key={name}><div className="workflow-icon">⌁</div><div><strong>{name}</strong><p>{desc}</p></div><span className="status running">{status}</span></article>)}</div></section>}
function History({rows,loading,money}:{rows:RevenueRow[];loading:boolean;money:(n:number)=>string}){return <section className="panel history-panel"><div className="panelhead"><div><div className="eyebrow">PAYMENT AUDIT</div><strong>Lịch sử giao dịch</strong></div><span className="label">payment_events · Supabase</span></div>{loading?<div className="history-loading">Đang tải dữ liệu thực tế…</div>:rows.length?<div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Mã GD</th><th>Số tiền</th><th>Thời gian</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.transactionCode}</strong><div className="label">{r.provider}</div></td><td className="amount">{money(r.amount)}</td><td>{r.createdAt?new Date(r.createdAt).toLocaleString("vi-VN"):"—"}</td><td><span className="status running">{r.status.toUpperCase()}</span></td></tr>)}</tbody></table></div>:<div className="empty">Chưa có giao dịch thành công được ghi nhận.</div>}</section>}
