export type AI04Product = {
  id: string; name: string; category: string; sourceFile: string;
  targetCustomer: string; problemSolved: string; licenseStatus: "review_required" | "approved" | "blocked";
  tags: string[]; relatedProducts: string[];
};
export const AI04_SEED_PRODUCTS: AI04Product[] = [
  {id:"ai-solopreneur-blueprint",name:"AI Solopreneur Blueprint",category:"Business Starter",sourceFile:"ai-solopreneur-blueprint",targetCustomer:"solopreneurs and beginners",problemSolved:"AI business planning",licenseStatus:"review_required",tags:["ai","solopreneur","business"],relatedProducts:["notion-business-os"]},
  {id:"notion-business-os",name:"Notion Business OS 1.0",category:"Business Starter",sourceFile:"notion-business-os-1.0",targetCustomer:"freelancers and small businesses",problemSolved:"business operating system",licenseStatus:"review_required",tags:["notion","business","operations"],relatedProducts:["ai-solopreneur-blueprint"]},
  {id:"b2b-linkedin-lead-bot",name:"B2B LinkedIn Lead Bot 1.0",category:"Marketing & Sales",sourceFile:"b2b-linkedin-lead-bot-1.0",targetCustomer:"B2B sales teams",problemSolved:"lead generation automation",licenseStatus:"review_required",tags:["linkedin","b2b","leads"],relatedProducts:["omni-channel-lead-sync"]},
  {id:"dify-seo-agent-kit",name:"Dify SEO Agent Kit 1.0",category:"Marketing & Sales",sourceFile:"dify-seo-agent-kit-1.0",targetCustomer:"marketers and agencies",problemSolved:"SEO workflow automation",licenseStatus:"review_required",tags:["dify","seo","content"],relatedProducts:["b2b-linkedin-lead-bot"]},
  {id:"automated-hr-resume-screening-kit",name:"Automated HR Resume Screening Kit",category:"Automation & Operations",sourceFile:"automated-hr-resume-screening-kit",targetCustomer:"HR teams and startups",problemSolved:"resume screening automation",licenseStatus:"review_required",tags:["hr","recruiting","automation"],relatedProducts:["omni-channel-lead-sync"]},
  {id:"omni-channel-lead-sync",name:"Omni-Channel Lead Sync & Auto-Qualifier",category:"Marketing & Sales",sourceFile:"Omni-Channel-Lead-Sync-Auto-Qualifier-Kit-v1.0.0",targetCustomer:"sales and growth teams",problemSolved:"lead sync and qualification",licenseStatus:"review_required",tags:["leads","crm","automation"],relatedProducts:["b2b-linkedin-lead-bot"]},
  {id:"local-competitor-radar",name:"Local Competitor Radar",category:"Automation & Operations",sourceFile:"local-competitor-radar",targetCustomer:"local businesses and agencies",problemSolved:"competitor monitoring",licenseStatus:"review_required",tags:["competitor","research","radar"],relatedProducts:["dify-seo-agent-kit"]},
  {id:"instant-digital-storefront",name:"Instant Digital Storefront",category:"AI Commerce",sourceFile:"instant-digital-storefront",targetCustomer:"digital sellers",problemSolved:"digital storefront setup",licenseStatus:"review_required",tags:["store","nextjs","vercel"],relatedProducts:["ecommerce-sales-support-agent"]},
  {id:"ecommerce-sales-support-agent",name:"E-commerce Sales & Support Agent System",category:"AI Commerce",sourceFile:"ecommerce-sales-support-agent-system-v1.0.0",targetCustomer:"online stores",problemSolved:"AI sales and customer support",licenseStatus:"review_required",tags:["ecommerce","sales","support"],relatedProducts:["instant-digital-storefront"]},
  {id:"n8n-code-security-scanner",name:"n8n Code Security Scanner 1.0",category:"Developer & Security",sourceFile:"n8n-code-security-scanner-1.0",targetCustomer:"developers and agencies",problemSolved:"n8n code security checks",licenseStatus:"review_required",tags:["n8n","security","developer"],relatedProducts:["instant-digital-storefront"]},
];